---
# Example: https://github.com/quarto-dev/quarto-web/blob/main/_quarto.yml
project:
  type: website
  output-dir: _site
  preview:
    port: 4200
    browser: false
  resources:
    - "/.nojekyll"
    - "/static/*"
  render:
    - "*.qmd"
    - "*.ipynb"
    - "*.Rmd"
    - "*.md"

execute:
  freeze: auto # Re-compute previously generated computational output only in case their source file changes

website:
  title: "Docs"
  description: "REMFluorMD-MD Technical Documentation"
  favicon: static/favicon.ico
  site-url: /remfluormd/docs/
  page-navigation: true
  back-to-top-navigation: false
  bread-crumbs: true
  repo-url: https://github.com/HirokoHort/0_REMFluorMD_64
  search:
    location: sidebar
    type: textbox
    copy-button: true
    keyboard-shortcut: ["/", "H"]
    show-item-context: true
  page-footer:
    left: "&copy; 2027 [GSI Environmental Inc.](https://gsienv.com)"
    center: |
      [![](/static/logo.svg){fig-alt="GSI Environmental Inc." width=65px}](https://gsienv.com)
    right: |
      [Have a question?](mailto:cgrant@gsi-net.com?subject="Anniston SMP Documentation Feedback")
  navbar:
    title: false
    collapse-below: lg
    left:
      - text: "REMFluor-MD Technical Documentation"
    tools:
      - icon: github
        text: GSI GitHub
        href: https://github.com/HirokoHort/0_REMFluorMD_64

  sidebar:
    - id: "sidebar"
      title: "Documentation"
      collapse-level: 1
      # style: "floating"
      contents:
        - section: "Appendices"
          contents:
            - href: appendix/appendix_2_1.qmd
            - href: appendix/appendix_2_2.qmd
            - href: appendix/appendix_3_1.qmd
            - href: appendix/appendix_4_1.qmd
            - href: appendix/appendix_4_2.qmd
            - href: appendix/appendix_5_1.qmd
            - href: appendix/appendix_5_2.qmd
            - href: appendix/appendix_5_3.qmd
            - href: appendix/appendix_6_1.qmd
            - href: appendix/appendix_7_1.qmd
            - href: appendix/appendix_8_1.qmd
            - href: appendix/appendix_9_1.qmd
            - href: appendix/appendix_9_2.qmd
            - href: appendix/appendix_10_1.qmd
            - href: appendix/appendix_11_1.qmd
            - href: appendix/appendix_11_2.qmd
        - section: "Data Chicklets"
          contents:
            - href: data_chicklets/Step1_SystemUnits.qmd
            - href: data_chicklets/Step2_ModelConfiguration.qmd
            - href: data_chicklets/Step3_GroundwaterDarcyVelocity.qmd
            - href: data_chicklets/Step4_HydrogeologicSettingAndMatrixDiffusion.qmd
            - href: data_chicklets/Step5_PFASTransportProperties.qmd
            - href: data_chicklets/Step6_PlumeTransport.qmd
            - href: data_chicklets/Step7_PFASSourceTerm.qmd
            - href: data_chicklets/Step8_SourceRemediation.qmd
            - href: data_chicklets/Step9_PlumeRemediationPSB.qmd
            - href: data_chicklets/Step10_FieldDataToCalibrate.qmd
            - href: data_chicklets/Step11_ModelingParameters.qmd
            - href: data_chicklets/SensitivityAnalysis.qmd
              text: "Sensitivity / Uncertainty Analysis"

format:
  html:
    theme:
      light: [cosmo, static/theme.scss]
    css: static/styles.css
    brand: _brand.yaml
    toc: true
    toc-depth: 3
    code-copy: true
    code-fold: true
    code-overflow: wrap
    code-line-numbers: false
    code-annotations: below
    highlight-style: static/github-dark.theme
    link-external-newwindow: true
    filters:
      - black-formatter
      - downloadthis
      - diagram
    grid:
      sidebar-width: 250px
      body-width: 1000px
      margin-width: 300px
