---
title: REMFluor-MD
description: Environmental Security Certification Program (ESTCP).
---

SAVE TEST5 The Anniston Soil Management Portal (SMP) is a web-based application designed to assist users in managing soil management decisions. It provides tools for visualizing soil data, generating reports, and accessing soil-related information.

The [SMP](./smp/index.qmd) Graphical User Interface (GUI) is built using R Shiny, providing an interactive and user-friendly experience. The backend [REST API](./api/index.qmd) handles all business logic, including geometry validation, chemistry data lookup, report creation, and asynchronous report generation.

Click on the sidebar to navigate to specific sections of the documentation.

## Resources

- [SMP](http://139.94.149.245/anniston/smp/) (`http://139.94.149.245/anniston/smp/`): The Soil Management Portal (SMP) is a web-based application designed to assist users in managing soil management decisions. It provides tools for visualizing soil data, generating reports, and accessing soil-related information.
- [API Documentation](http://139.94.149.245/anniston/api/docs/) (`http://139.94.149.245/anniston/api/docs/`): The API documentation provides detailed information about the RESTful API endpoints available for interacting with the Anniston Soil Management Portal. It includes information on how to access soil data programmatically, perform queries, and retrieve soil-related information.
- [Documentation](http://139.94.149.245/anniston/docs/) (`http://139.94.149.245/anniston/docs/`): The documentation provides detailed information about the Anniston Soil Management Portal, including installation instructions, configuration options, and usage guidelines.
